# Generated by Django 2.0 on 2018-01-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_stripe_id_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='strip_id',
        ),
    ]
