# Generated by Django 2.0.2 on 2018-02-11 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deleted_stripe_id_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=datetime.datetime(2018, 2, 11, 23, 23, 56, 810216, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
