# Generated by Django 2.0.2 on 2018-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180215_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
